name: GetManager
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: read   # Allows triggering actions

on:
  workflow_call: # This allows this workflow to be called from another workflow
    inputs:
      kernelsu_variant:
        required: false
        type: string
        default: SukiSU

jobs:
  get_ksu_manager:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: 安装依赖
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y git curl jq

      - name: 下载 KernelSU 管理器
        run: |
          if [ "${{ inputs.kernelsu_variant }}" == "Next" ]; then
            echo "KernelSU Next..."
            REPO="KernelSU-Next/KernelSU-Next"
            FILENAME="build-manager-ci.yml"
            BRANCH="next"
          elif [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
            echo "SukiSU..."
            REPO="SukiSU-Ultra/SukiSU-Ultra"
            FILENAME="build-manager.yml"
            BRANCH="main"
          fi

          # 获取最新成功构建的 ID
          BUILD_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$REPO/actions/workflows/$FILENAME/runs?event=push&status=success&branch=$BRANCH" | \
            jq -r '.workflow_runs[0].id')
          echo 'BUILD_ID=$BUILD_ID'
          # 获取该构建的 Artifacts
          ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/actions/runs/$BUILD_ID/artifacts")
          echo 'ARTIFACTS=$ARTIFACTS'
          # 获取 Manager 文件的下载链接
          DOWNLOAD_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name == "Manager") | .archive_download_url')

          # 下载 Manager 文件
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o "${{ inputs.kernelsu_variant }}-管理器.zip" "$DOWNLOAD_URL"
          echo "Manager 文件已下载为：${{ inputs.kernelsu_variant }}-管理器.zip"
          unzip *.zip

      - name: 上传编译资产
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.kernelsu_variant }}-Manager
          path: |
            *.apk
