name: Android 14 5.15
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      kernelsu_variant:
        required: false
        type: string
        default: SukiSU
      kernelsu_branch:
        required: true
        type: string
        default: Stable(标准)
      version:
        required: false
        type: string
        default: ""
      use_zram:
        description: '是否开启增加更多ZRAM算法?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: '是否开启KPM功能?'
        required: false
        type: boolean
        default: false
      supp_op:
        description: '是否开启一加8E处理器机型支持?(非该机型无须勾)'
        required: false
        type: boolean
        default: false
      lz4_upd:
        description: "是否升级LZ4算法至1.10.0?"
        required: true
        type: boolean
        default: true
      use_O3:
        description: "是否开启O3编译优化?"
        required: true
        type: boolean
        default: true
      BBG:
        description: '是否启用内核层面阻止对关键分区/设备节点的非法写入(LSM)？'
        required: true
        type: boolean
        default: true
  
jobs:
  build-kernel-a14-5-15-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "131"
          #  os_patch_level: "2023-11"
          #- sub_level: "137"
          #  os_patch_level: "2024-01"
          #- sub_level: "144"
          #  os_patch_level: "2024-03"
          #- sub_level: "148"
          #  os_patch_level: "2024-05"
          #- sub_level: "153"
          #  os_patch_level: "2024-07"
          #- sub_level: "158"
          #  os_patch_level: "2024-08"
          #- sub_level: "167"
          #  os_patch_level: "2024-11"
          #- sub_level: "170"
          #  os_patch_level: "2025-01"
          #- sub_level: "178"
          #  os_patch_level: "2025-03"
          #- sub_level: "180"
          #  os_patch_level: "2025-05"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      supp_op: ${{ inputs.supp_op }}
      lz4_upd: ${{ inputs.lz4_upd }}
      use_O3: ${{ inputs.use_O3 }}
      BBG: ${{ inputs.BBG }}
